prettier fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,78 +23,78 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  nf-test-changes:
-    name: Check for changes
-    runs-on: ubuntu-latest
-    outputs:
-      nf_test_files: ${{ steps.list.outputs.components }}
-      # nf_test_files: ${{ env.TEST_SET }}
+  #  nf-test-changes:
+  #    name: Check for changes
+  #    runs-on: ubuntu-latest
+  #    outputs:
+  #      nf_test_files: ${{ steps.list.outputs.components }}
+  #      # nf_test_files: ${{ env.TEST_SET }}
+  #
+  #    steps:
+  #      - uses: actions/checkout@v4
+  #        with:
+  #          fetch-depth: 0
+  #
+  #      - name: List nf-test files
+  #        id: list
+  #        uses: adamrtalbot/detect-nf-test-changes@v0.0.4
+  #        with:
+  #          head: ${{ github.sha }}
+  #          # TODO: check that the following works on pull_request
+  #          base: ${{ github.ref_name }}
+  #
+  #      - name: print list of nf-test files
+  #        run: |
+  #          echo ${{ steps.list.outputs.components }}
 
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: List nf-test files
-        id: list
-        uses: adamrtalbot/detect-nf-test-changes@v0.0.4
-        with:
-          head: ${{ github.sha }}
-          # TODO: check that the following works on pull_request
-          base: ${{ github.ref_name }}
-
-      - name: print list of nf-test files
-        run: |
-          echo ${{ steps.list.outputs.components }}
-
-  test:
-    name: "Run tests (${{ matrix.nf_test_files }} ${{ matrix.profile }} NF-${{ matrix.NXF_VER }})"
-    needs: [nf-test-changes]
-    # Only run on push if this is the nf-core dev branch (merged PRs)
-    if: "${{ (github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/mcmicro')) && needs.nf-test-changes.outputs.nf_test_files != '[]' }}"
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        NXF_VER:
-          - "24.04.2"
-          - "latest-everything"
-        nf_test_files: ["${{ fromJson(needs.nf-test-changes.outputs.nf_test_files) }}"]
-        profile:
-          # - "conda"
-          - "docker"
-          - "singularity"
-        test_name:
-          - "test"
-        isMaster:
-          - ${{ github.base_ref == 'master' }}
-        # Exclude conda and singularity on dev
-        exclude:
-          - isMaster: false
-            profile: "conda"
-          - isMaster: false
-            profile: "singularity"
-    steps:
-      - name: install curl
-        run: sudo apt update && sudo apt install -y curl wget
-
-      - name: Check out pipeline code
-        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
-
-      - name: Set up Nextflow
-        uses: nf-core/setup-nextflow@v2
-        with:
-          version: "${{ matrix.NXF_VER }}"
-
-      - name: Set up Apptainer
-        if: matrix.profile == 'singularity'
-        uses: eWaterCycle/setup-apptainer@main
-
-      - name: Set up Singularity
-        if: matrix.profile == 'singularity'
-        run: |
-          mkdir -p $NXF_SINGULARITY_CACHEDIR
-          mkdir -p $NXF_SINGULARITY_LIBRARYDIR
+  #  test:
+  #    name: "Run tests (${{ matrix.nf_test_files }} ${{ matrix.profile }} NF-${{ matrix.NXF_VER }})"
+  #    needs: [nf-test-changes]
+  #    # Only run on push if this is the nf-core dev branch (merged PRs)
+  #    if: "${{ (github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/mcmicro')) && needs.nf-test-changes.outputs.nf_test_files != '[]' }}"
+  #    runs-on: ubuntu-latest
+  #    strategy:
+  #      fail-fast: false
+  #      matrix:
+  #        NXF_VER:
+  #          - "24.04.2"
+  #          - "latest-everything"
+  #        nf_test_files: ["${{ fromJson(needs.nf-test-changes.outputs.nf_test_files) }}"]
+  #        profile:
+  #          # - "conda"
+  #          - "docker"
+  #          - "singularity"
+  #        test_name:
+  #          - "test"
+  #        isMaster:
+  #          - ${{ github.base_ref == 'master' }}
+  #        # Exclude conda and singularity on dev
+  #        exclude:
+  #          - isMaster: false
+  #            profile: "conda"
+  #          - isMaster: false
+  #            profile: "singularity"
+  #    steps:
+  #      - name: install curl
+  #        run: sudo apt update && sudo apt install -y curl wget
+  #
+  #      - name: Check out pipeline code
+  #        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
+  #
+  #      - name: Set up Nextflow
+  #        uses: nf-core/setup-nextflow@v2
+  #        with:
+  #          version: "${{ matrix.NXF_VER }}"
+  #
+  #      - name: Set up Apptainer
+  #        if: matrix.profile == 'singularity'
+  #        uses: eWaterCycle/setup-apptainer@main
+  #
+  #      - name: Set up Singularity
+  #        if: matrix.profile == 'singularity'
+  #        run: |
+  #          mkdir -p $NXF_SINGULARITY_CACHEDIR
+  #          mkdir -p $NXF_SINGULARITY_LIBRARYDIR
 
   #      - name: Set up Miniconda
   #        if: matrix.profile == 'conda'
@@ -172,7 +172,7 @@ jobs:
   #          echo "toJSON(needs) = ${{ toJSON(needs) }}"
   #          echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"
 
-  test_orig:
+  test:
     name: Run pipeline with test data
     # Only run on push if this is the nf-core dev branch (merged PRs)
     if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/mcmicro') }}"
